spring.application.name=jornaldb
server.port=8081

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/journaldb

# MySQL username
spring.datasource.username=root

# MySQL password
spring.datasource.password=amit12345678

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
weather.api.key=62a2da6f1e7bcc57060e795c33a4e2c2
#spring.application.name=jornaldb
#
#spring.profiles.active=dev